In [1]:
import numpy as np
import pandas as pd
import os

In [3]:
db_pack = pd.read_csv('D:\data\Aaron\ProstateMRL\Data\MRLPacks\ScanInfo\Allpacks.csv')
db_20f = pd.read_csv('D:\data\Aaron\ProstateMRL\Data\Extraction\patientDatainfo\scaninfo_20fractions.csv')
db_SABR = pd.read_csv('D:\data\Aaron\ProstateMRL\Data\Extraction\patientDatainfo\scaninfo_SABR.csv')

In [5]:
ids_pack = db_pack.Patient.unique()
ids_20f = db_20f.Patient.unique()
ids_SABR = db_SABR.Patient.unique()

print(ids_pack)
print(ids_20f)
print(ids_SABR)

[1088 1089 1118 1303 1307  653  713  714  752  826  213  232  257  292]
[   213    231    257    292    626    695   1464 106958 251842 312108]
[ 653  713  752  826 1088 1089 1118 1303 1307 1464]


In [32]:
ids_20f = list(set(ids_pack).intersection(ids_20f))
ids_SABR = list(set(ids_pack).intersection(ids_SABR))

print(ids_20f)
print(ids_SABR)

ids_SABR = [1088]

[257, 292, 213]
[1088]


In [56]:
ids_SABR = [1088]
for i in ids_SABR:
    print(i)
    df_pack_p = db_pack[db_pack['Patient'].isin([i])]
    df_SABR_p = db_SABR[db_SABR['Patient'].isin([i])]

    dates = df_SABR_p.DateofScan.unique()
    
    for d in dates:
        print(d)
        df_packs_d = df_pack_p[df_pack_p['DateofScan'].isin([d])]
        #df_SABR_d = df_SABR_p[df_pack_p['DateofScan'].isin([d])]
        
        time = df_SABR_d.TimeofScan.unique()
        print(time)
        time = pd.to_datetime(time)
        print(time)
        
        # for i in range(len(df_packs_d)):
        #     df_packs_d["TimeDiff"] = 
    
        



1088
20120530
[143057.56]
DatetimeIndex(['1970-01-01 00:00:00.000143057'], dtype='datetime64[ns]', freq=None)
20120601
[143057.56]
DatetimeIndex(['1970-01-01 00:00:00.000143057'], dtype='datetime64[ns]', freq=None)
20120603
[143057.56]
DatetimeIndex(['1970-01-01 00:00:00.000143057'], dtype='datetime64[ns]', freq=None)
20120606
[143057.56]
DatetimeIndex(['1970-01-01 00:00:00.000143057'], dtype='datetime64[ns]', freq=None)
20120511
[143057.56]
DatetimeIndex(['1970-01-01 00:00:00.000143057'], dtype='datetime64[ns]', freq=None)
